config/routes.rb
TemplateSite::Application.routes.draw do

  scope '(:locale)' do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    root 'static_pages#home'

    scope module: :web do
      namespace :auth do
        resources :sessions, only: [:new, :create, :destroy]
        match '/signin',  to: 'sessions#new',         via: 'get'
        match '/signout', to: 'sessions#destroy',     via: 'delete'
      end
    end
  end

  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  before_create :create_remember_token

  has_secure_password

  validates :password, presence: true, length: { minimum: 6 }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def User.create_first_admin
    first_admin = User.new(name: "admin", email: "admin@admin.ru", password: "admin", password_confirmation: "admin")
    first_admin.save(validate: false)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :set_i18n_locale_from_params


  add_breadcrumb (I18n.t "application.controller.home"), :root_path

  protect_from_forgery with: :exception
  include Web::Auth::SessionsHelper

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def not_authenticated
    # Make sure that we reference the route from the main app.
    # redirect_to admin_signin_path
    redirect_to auth_signin_path
  end

  protected
    def set_i18n_locale_from_params
      if params[:locale]
        if I18n.available_locales.include?(params[:locale].to_sym)
          I18n.locale = params[:locale]
        else
          flash[:warning] = "#{params[:locale]} translation not available"
          logger.error flash[:warning]
        end
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    #base_title = MyAppSettings.title
    base_title = configus.app_title
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/web/admin/sessions_helper.rb
module Web::Admin::SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    @current_user = user
  end

  def sign_out
    @current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    if signed_in? == false
      store_location
      flash[:notice] = "Пожалуйста авторизуйтесь."
      redirect_to admin_signin_path
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end  

  def signed_in?
    !current_user.nil?
  end
end

app/views/layouts/_footer.html.erb
<footer>

  <div class="author-rights">
    &#169; 2014 laboq inc,  All Rights Reserved</br>
    &#169; 2014 Галиуллов Альберт
  </div>
  <!--<ul class="social-icons">
    <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
    <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
    <li><a class="rss" href="#"><i class="fa fa-rss"></i></a></li>
    <li><a class="google" href="#"><i class="fa fa-google-plus"></i></a></li>
    <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
    <li><a class="pinterest" href="#"><i class="fa fa-pinterest"></i></a></li>
  </ul>-->
</footer>

app/views/layouts/_header.html.erb
<!-- Header
  ================================================== -->
<header>
	<div class="left-part">
		<a class="logo" href="#"><img alt="" src="<%= asset_path 'laboq/logo.png' %>"></a>
	</div>
	<div class="right-part">
		<div class="menu-box">
			<ul class="menu">
				<!--<li><a class="active" href="index.html"><span>Home</span></a></li>-->
				<li>
				  <%= link_to root_path, class: "active" do %>
            <span><%= (I18n.t "application.controller.home") %></span>
          <% end %>
        </li>
				<li><a href="#"><span>About</span></a></li>
				<li class="drop"><a href="#"><span>blog</span></a>
					<ul class="drop-down">
						<li><a href="#"><span>Blog</span></a></li>
						<li><a href="#"><span>Blog with sidebar</span></a></li>
						<li><a href="#"><span>Single Post</span></a></li>
					</ul>
				</li>
				<li><a href="#"><span>Contact</span></a></li>
			</ul>				
		</div>

		<div class="contact-info-box">
			<h1>Contact Info</h1>
			<p>
				<span><i class="fa fa-envelope-o"></i>support@convertible.com</span>
				<span><i class="fa fa-phone"></i>1234 - 5678 - 9012</span>
			</p>

	    <div class="nav-collapse pull-right">
	      <div class="btn-group">
	      	<% if signed_in? %>
				    <button type="button" class="btn btn-default"><%= link_to (I18n.t "application.view.layouts.header.logout"), auth_signout_path, method: "delete" %></button>
				  
				    <!--<button type="button" class="btn btn-default"><%= link_to (I18n.t "application.view.layouts.header.login"), auth_signin_path %></button>-->
				  <% end %>
				</div>
	    </div>
		</div>

	</div>

<div></div>
<ol class="breadcrumb">
	<%= render_breadcrumbs :tag => :li, :separator => "" %>
</ol>

</header>
<!-- End Header -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>


<html lang="ru" class="no-js">
<head>
  <title><%= full_title(yield(:title)) %></title>

  <meta charset="utf-8">

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>

  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <!-- Container -->
  <div id="container">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>

<!--
  <div class="preloader">
    <img alt="" src="<%= asset_path 'preloader.GIF' %>">
  </div>
-->

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, (I18n.t "application.view.shared.error_messages.erorrs")) %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<%= provide(:title, 'Home') %>
		<!-- content 
			================================================== -->
		<div id="content">
			<div class="inner-content">

				<div class="about-page">
					<div class="container">
						<div class="row">
							<div class="col-md-9">
								<div class="about-content">
									<img alt="" src="#" style="width: 350px; height=300px; float: left; margin: 0px 20px 0px 0px;">
									<h1>About company</h1>
									<p>Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. </p>
									<p>Sed non  mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. </p>
									<p>Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit. Sed ut imperdiet nisi. Proin condimentum fermentum nunc. Etiam pharetra, erat sed fermentum feugiat, velit mauris egestas quam, ut aliquam massa nisl quis neque. Suspendisse in orci enim.</p>
								</div>
							</div>

							<div class="col-md-3 sidebar">							
								<div class="widget doing-list-widget">
									<h2>Services</h2>
									<ul class="doing-list">
										<li><span>website design</span></li>
										<li><span>Photography</span></li>
										<li><span>plugin development</span></li>
										<li><span>Front End</span></li>
										<li><span>Design from Scratch</span></li>
										<li><span>Website Maintenance</span></li>
									</ul>
								</div>
							</div>

							<div style="clear: both;"></div>
							
						</div>
					

						<div class="row">
							<div class="col-md-12">			
								<div class="portfolio-box">
									<h1>Our portfolio</h1>

									<div class="project-post">
										<div class="galery-box">
											<a href="upload/1.jpg" class="zoom">
												<img alt="" src="upload/1.jpg">
												<span>logo</span>
											</a>							
										</div>
										<div class="content-box">
											<h2><a href="single-project.html">Creative Brand Design</a></h2>
											<p>logo design for lorem company</p>
										</div>
									</div>

									<div class="project-post">
										<div class="galery-box">
											<a href="upload/2.jpg" class="zoom">
												<img alt="" src="upload/2.jpg">
												<span>logo</span>
											</a>							
										</div>
										<div class="content-box">
											<h2><a href="single-project.html">Creative Brand Design</a></h2>
											<p>logo design for lorem company</p>
										</div>
									</div>

									<div class="project-post">
										<div class="galery-box">
											<a href="upload/3.jpg" class="zoom">
												<img alt="" src="upload/3.jpg">
												<span>logo</span>
											</a>							
										</div>
										<div class="content-box">
											<h2><a href="single-project.html">Creative Brand Design</a></h2>
											<p>logo design for lorem company</p>
										</div>
									</div>

									<div class="project-post">
										<div class="galery-box">
											<a href="upload/3.jpg" class="zoom">
												<img alt="" src="upload/3.jpg">
												<span>logo</span>
											</a>							
										</div>
										<div class="content-box">
											<h2><a href="single-project.html">Creative Brand Design</a></h2>
											<p>logo design for lorem company</p>
										</div>
									</div>

								</div>
							</div>
						</div>
						<a class="show-more" href="#">Show more</a>

					</div>
				</div>
			</div>
		</div>
		<!-- End content -->